### ISSUE TITLE
GitClone/GitPush usage before git installation instructions

### ISSUE THREAD

**Issue by SvitlanaDidkivska** [stalj/data-notations#2]
In Chapter 01 there are instructions (GitClone/GitPush), which imply that the user already have Git on a computer installed and is ready to use it. There are such commands, like `git add`, `git config`, `git push` etc.
At the same time the instruction, that explains how to install git is available in the Chapter 02.

IMO, it would be better to place tasks from chapter 01 after the explanation how to install git.

**Comment by stalj** [comment]
Do you mean those 2 pptx files in 01-CourseIntroduction? We can remove them cause they are added last year, just in case.

**Comment by stalj** [comment]
Chapter 01 is only for introductory classes, say smothing on course syllabus, how to pass the course, etc There are not regular class topics. Frankly, course starts from 02.

**Comment by SvitlanaDidkivska** [comment]
In that case, it is ok.
My apologies. It was a little confusing to me to find git commands in the presentation before an initial git configuration. 😄
