### ISSUE TITLE
Default branch naming

### ISSUE THREAD

**Issue by SvitlanaDidkivska** [stalj/data-notations#3]
The main branch name could have a different name on the student's computer: `main` or `master`. It depends on the installation method and basic configuration preferences. Source: [https://www.theserverside.com/feature/Why-GitHub-renamed-its-master-branch-to-main](https://www.theserverside.com/feature/Why-GitHub-renamed-its-master-branch-to-main). It can cause some difficulties and misunderstanding why the command `git checkout master` is not working.

IMO, it is a good place to inform students about the ability to change the default branch name.

**Comment by stalj** [comment]
After adding a note to class materials I think we can close this issue.
